In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("../src/afterCleaning_data.csv")
data.head()

,title,location,price(L),rate_persqft,area_insqft,building_status
0,3 BHK Apartment,Nizampet,108.00,6000,1805,Under Construction
1,3 BHK Apartment,Bachupally,85.80,5500,1560,Under Construction
2,2 BHK Apartment,Dundigal,55.64,5200,1070,Under Construction
3,2 BHK Apartment,Pocharam,60.48,4999,1210,Under Construction
4,3 BHK Apartment,Kollur,113.00,5999,1900,Under Construction

In [5]:
data.shape

(3660, 6)

In [6]:
data = pd.get_dummies(
    data,
    columns=['title','location','building_status'],
    dtype=int
)
data.head()

,price(L),rate_persqft,area_insqft,title_1 BHK Apartment,title_1 BHK Independent House,title_1 RK Studio Apartment,title_10 BHK Independent House,title_2 BHK Apartment,title_2 BHK Independent Floor,title_2 BHK Independent House,...,location_Yacharam Mandal,location_Yadadri Colony Road,location_Yadagirigutta,location_Yapral,location_Yousufguda,location_Zaheerabad,building_status_New,building_status_Ready to move,building_status_Resale,building_status_Under Construction
0,108.00,6000,1805,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,85.80,5500,1560,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,55.64,5200,1070,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,60.48,4999,1210,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,113.00,5999,1900,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [7]:
data.shape

(3660, 390)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3660 entries, 0 to 3659
Columns: 390 entries, price(L) to building_status_Under Construction
dtypes: float64(1), int64(389)
memory usage: 10.9 MB

In [10]:
data.to_csv("../src/afterFeatureEngineering_data.csv",index=False)