In [9]:
import pandas as pd

In [10]:
import sys
sys.path.append("..")
from src.load_data import load_data
data = load_data()
data.head()

,Unnamed: 0,title,location,price(L),rate_persqft,area_insqft,building_status
0,0,3 BHK Apartment,Nizampet,108.00,6000,1805,Under Construction
1,1,3 BHK Apartment,Bachupally,85.80,5500,1560,Under Construction
2,2,2 BHK Apartment,Dundigal,55.64,5200,1070,Under Construction
3,3,2 BHK Apartment,Pocharam,60.48,4999,1210,Under Construction
4,4,3 BHK Apartment,Kollur,113.00,5999,1900,Under Construction

location feature -- Text Standardization

In [11]:
data['location'].nunique()

359

In [12]:
data['location'] = data['location'].str.strip().str.title()

In [13]:
data['location'].nunique()

358

Outliers do exist ( in columns : price, rate persft, area insqft ) : but they look like natural, genuine variations - so keeping it untouched

In [14]:
data = data.drop(columns=['Unnamed: 0'])
data.head()

,title,location,price(L),rate_persqft,area_insqft,building_status
0,3 BHK Apartment,Nizampet,108.00,6000,1805,Under Construction
1,3 BHK Apartment,Bachupally,85.80,5500,1560,Under Construction
2,2 BHK Apartment,Dundigal,55.64,5200,1070,Under Construction
3,2 BHK Apartment,Pocharam,60.48,4999,1210,Under Construction
4,3 BHK Apartment,Kollur,113.00,5999,1900,Under Construction

In [16]:
data.to_csv("../src/afterCleaning_data.csv",index=False)