In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../src/afterFeatureEngineering_data.csv")
data.head()

,price(L),rate_persqft,area_insqft,title_1 BHK Apartment,title_1 BHK Independent House,title_1 RK Studio Apartment,title_10 BHK Independent House,title_2 BHK Apartment,title_2 BHK Independent Floor,title_2 BHK Independent House,...,location_Yacharam Mandal,location_Yadadri Colony Road,location_Yadagirigutta,location_Yapral,location_Yousufguda,location_Zaheerabad,building_status_New,building_status_Ready to move,building_status_Resale,building_status_Under Construction
0,108.00,6000,1805,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,85.80,5500,1560,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,55.64,5200,1070,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
3,60.48,4999,1210,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
4,113.00,5999,1900,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [3]:
x = data.drop(columns=['price(L)'])
x.head()

,rate_persqft,area_insqft,title_1 BHK Apartment,title_1 BHK Independent House,title_1 RK Studio Apartment,title_10 BHK Independent House,title_2 BHK Apartment,title_2 BHK Independent Floor,title_2 BHK Independent House,title_2 BHK Villa,...,location_Yacharam Mandal,location_Yadadri Colony Road,location_Yadagirigutta,location_Yapral,location_Yousufguda,location_Zaheerabad,building_status_New,building_status_Ready to move,building_status_Resale,building_status_Under Construction
0,6000,1805,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,5500,1560,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,5200,1070,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4999,1210,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,5999,1900,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
y = data['price(L)']
y.head()

0    108.00
1     85.80
2     55.64
3     60.48
4    113.00
Name: price(L), dtype: float64

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
# print("training set of x :",x_train)
# print("training set of y :",y_train)
# print("testing set of x :",x_test)
# print("testing set of y :",x_test)

In [6]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(2928, 389)
(2928,)
(732, 389)
(732,)

In [7]:
x_train.to_csv("../src/x_train.csv",index=False)
y_train.to_csv("../src/y_train.csv",index=False)
x_test.to_csv("../src/x_test.csv",index=False)
y_test.to_csv("../src/y_test.csv",index=False)